- name: Deploy to Tomcat
  hosts: web
  become: yes

tasks:
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/home/unified/mavenansible/target/mavenansible.war"
        dest: "/opt/tomcat/webapps/mavenansible.war"
        remote_src: no

  - name: Restart Tomcat
    service:
      name: tomcat
      state: restarted
